/* automatically generated by configure */
/* edit configure.in to change the version number */
#define SPINDLE_MAJOR_VERSION 0
#define SPINDLE_MINOR_VERSION 0
#define SPINDLE_BUGFIX_VERSION 1
#define SPINDLE_EXTRA_VERSION "-dev"
#define SPINDLE_VERSION_TEXT "0.0.1-dev"
#define SPINDLE_VERSION_ID 1
